name: Build documentation

on:
  pull_request:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Build the documentation
        run: |
          pip install -r requirements.txt
          sphinx-build docs docs/_build/html

      # ref: https://github.com/lycheeverse/lychee-action
      # ref: https://github.com/lycheeverse/lychee#commandline-parameters
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.4
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          fail: true
          # github.com link below: This is a known fail
          args: >
            docs/_build/**/*.html
            --insecure
            --max-retries 10
            --exclude-link-local
            --exclude mailto
            --exclude https://github.com/executablebooks/meta/edit/master/docs/contributing.md
          jobSummary: true
